### ISSUE TITLE
Missing API documentation for SFFSegmentation

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk-rw#1]
The API documentation for the classes does not appear on the web site:

https://sfftk-rw.readthedocs.io/en/latest/adapter.html#sffsegmentation-class

The class names such as SFFSegmentation are listed by no methods are described.

**Comment by paulkorir** [comment]
Fixed in df30c05b852c5b05826a45997f9a79f8e7a555bc
