### ISSUE TITLE
SFFSegment.meshes is None

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk-rw#3]
Some list attributes such as SFFSegment.meshes and SFFSegment.shapes in emd_1547.sff are None.  It would make more sense if they were empty lists.  This allows code that iterates over them or asks for their length to work.

**Comment by paulkorir** [comment]
Now available in branch `feature/v0.8` soon to be merged into master. Applies to all `SFF*List` classes.
