### ISSUE TITLE
Package name sfftkrw.schema.adapter should be simpler

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk-rw#4]
The package hierarchy sfftkrw.schema.adapter and sfftkrw.schema.base seem to be mostly concerned with the implementation details, something about the use of generateDS.  The user of sfftkrw should not need to know anything about that.  I would expect all the classes like SFFSegmentation, SFFMesh, ... to reside in sfftkrw.  This will make it as simple for the developer to use as possible.

**Comment by paulkorir** [comment]
In the soon to be merged `feature/v0.8` branch we now have:

```
from sfftkrw import api

seg = api.SFFSegmentation(name="something")
```

**Comment by tomgoddard** [comment]
Why not

from sfftkrw import SFFSegmentation

**Comment by paulkorir** [comment]
Done.
