### ISSUE TITLE
Pip install fails for Python 3.9

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk-rw#6]
Can the sfftk-rw pypi dependency list be updated to use h5py version 3 so that it can be used with Python 3.9?

sfftk-rw depends on PyPi package h5py and requires version < 3.  It tries to install h5py 2.10 from 2019 and that version has no wheels for Python 3.9 since it is from before Python 3.9 existed.  The current version of h5py is 3.2.1.  I don't know if there were h5py API changes in going from version 2 to version 3 that will affect sfftk-rw.

I'd like sfftk-rw to work with Python 3.9 because our next ChimeraX release will use Python 3.9 and I would like to not have to take the sff file reader out of ChimeraX.

**Comment by paulkorir** [comment]
Thanks, Tom. I'll give this attention. Any critical deadlines?

**Comment by tomgoddard** [comment]
No near deadlines.  We are just releasing ChimeraX 1.2 this month that uses Python 3.8 and that works with ssfftk-rw, and in about a month we will be migrating ChimeraX daily builds to Python 3.9 and ChimeraX 1.3 will be released in about 6 months.  So would be nice to have sfftk-rw working with Python 3.9 within 6 months.

**Comment by paulkorir** [comment]
Thanks, Tom for the clarification. I'll schedule it to be done way before that timeline comes to an end.

**Comment by paulkorir** [comment]
This should now be OK. There is a new stable `v0.7.0` available from PyPI but only for Python 3.6+. Please open a new ticket if you spot any new bugs.

**Comment by tomgoddard** [comment]
Tested install of 0.7.0.post1 into ChimeraX with Python 3.9.5 and it worked and correctly opened test data file emd_1014.hff.

Thanks!
